### ISSUE TITLE
Promotion for Collective Intelligence Residency

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#10]
## Acceptance

- [ ] CI Residency begins

## Tasks 

- [x] @theo-cox to talk to MIC about making an audio to create a promo video
- [ ] Posts for IG/FB/TW

**Comment by theo-cox** [comment]
WONTFIX. MIC didn't respond and this is basically a closed residency anyway.
