### ISSUE TITLE
Getting On Podcasts

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#12]
Just as much as creating our own podcast will build brand awareness, getting on other podcasts will this as well and give us more content to share. Being feature builds reputation fast and can lead to a strong momentum of growth. 

## Acceptance 

- [ ] First Podcast Feature Published
- [ ] Other Interviews Lined Up 
- [ ] SOP for Podcast Collaborations created 

## Tasks

- [x] Create list of potential podcasts - https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1186866634
- [ ] Draft pitch email 
- [ ] Sign up to Matchmaker.fm - https://www.matchmaker.fm/#features 
- [ ] Check - https://www.facebook.com/groups/109831329700952/ & https://www.facebook.com/groups/234007497618342

**Pitch Email**

Hi X,

A quick bit of background - [insert your area of expertise and credentials here]

I’ve been following your podcast for a while, and I really enjoyed your recent interview with [X] on how to achieve [Y]. I’ve already had some success using some of the tips they mentioned!

I wondered if you might be interested in having me on your show to talk about [insert something likely to be of value to their audience]

Here’s what I could cover:

[Specific point / tip you can share]
[Specific point / tip you can share]
[Specific point / tip you can share]
Let me know your thoughts!
[Your name]

**Tips**

Include Calendly link to be able to book interview.
Follow up 3 and 14 days later.

**Comment by theo-cox** [comment]
@nathenf drafted list - let me know if helpful

**Comment by nathenf** [comment]
@theo-cox thanks. I would like to try and expand this and go into more detail on each persons authority on the talking points

**Comment by nathenf** [comment]
Steve Glaveski agreed to interview Rufus for Future Squared Podcast 👍

**Comment by theo-cox** [comment]
Great!
