### ISSUE TITLE
Blog and Publication Features 

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#13]
## Acceptance

- [ ] Get featured on 10 websites (including backlinks)

## Tasks

- [ ] Theo, Rufus, and Liam to sign up for HARO - https://www.helpareporter.com/
- [ ] Search for publications open to guest posts 

https://loganix.com/guest-blogging-opportunities/
