### ISSUE TITLE
Centralizing Residency Content

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#15]
I have created a space in the comms folder to attempt to centralize all the content that we have available for the residencies and to create order moving forward. This will be a space for us, but also any participants who want to share photos/videos etc. 

It would be good to have a team effort on shifting all content from previous residencies into the folders and then using them from now on as well. 

## Acceptance

- [ ] All content from previous residencies centralized in the folders provided
- [ ] Team briefed on using these folders moving forward

## Tasks

- [ ] Add content from previous residencies
- [ ] Update Residency Content Capture SOP with directions on storage and organization

**Comment by theo-cox** [comment]
Happy to take your lead on this @nathenf so if you feel this is the best way to go then let's do it. My 2c, however, is that it would be easier and more intuitive to have content folders in the folder for each Sympoiesis residency rather than separate from all the rest of the content. To me the problem to fix is that there's nothing in the sub-folders here: https://drive.google.com/drive/folders/1dBb-NCAPoPvl5JRTjCfsYE7O2emWlRDa rather than that we don't have a folder in the comms drive.

As I said though, your call, so happy to hear your thoughts and go with what you think is best

**Comment by nathenf** [comment]
Yeah I can see your point too, although I believe that the content will outlive the rest of the files and then any content we do have from these residencies will be lost for eternity. Since most content from a residency will be used post event it will be much easier to find through the content folder. 

Taking both points into account, I would suggest we create the folders in content, but then make sure we add a shortcut to the main Sympoeisis folders. That way it is easy to navigate to regardless of where you come at it and when the Sympoeisis folders become deprecated all the content still remains in the content folder.

**Comment by theo-cox** [comment]
Happy with that man, thanks for the input!

**Comment by theo-cox** [comment]
Also @nathenf I have asked Valerie to add the content from Sympoiesis 1 and 2 to the folders (I couldn't find it on the shared drive myself). As you've got most of the Sympoiesis 3 content can you handle that? Cheers

**Comment by nathenf** [comment]
I've asked Julie to move the photos from Google photos to the drive.

**Comment by nathenf** [comment]
@theo-cox https://docs.google.com/document/d/1_W5_6E_0VOPNITXPNDAbUTEN19JELOc4qc3IYURlZUE/edit#heading=h.n8ni6smj8hlv this is now ready to be shared including the storage procedures

**Comment by theo-cox** [comment]
Perfect, cheers!
