### ISSUE TITLE
Optimizing Medium and Adding Articles

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#17]
Medium is a great way to link back to our main website and reach a new audience. However, we must share original content here and not content from the website. There are also some alternatives to Medium, which may be valuable to explore as well https://bloggingguide.com/medium-alternatives/. 

## Acceptance

- [ ] Medium optimized for use
- [ ] 5 great articles published here
- [ ] Followers increased to 30 

## Tasks 

- [ ] Nathen to optimize the profile
- [ ] Nathen to write SOP for writing and posting
- [ ] @theo-cox to draft or assign 5 articles 
- [ ] Nathen to publish articles 
- [ ] Nathen to promote articles and Medium across the Comms ecosystem

**Comment by nathenf** [comment]
WONT FIX - Low priority and not important
