### ISSUE TITLE
Welcome journey for new newsletter subscribers

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#2]
## Acceptance

- [ ] Welcome journey drafted
- [ ] Welcome journey implemented in our newsletter platform

## Tasks

- [ ] Draft bullets for welcome journey text **@theo-cox**
- [ ] Write up full welcome journey
- [ ] Implement welcome journey

**Comment by theo-cox** [comment]
@nathenf see here for the issue for this task. Click edit to view how I've written it. In general we want a new issue for each discrete task.

**Comment by nathenf** [comment]
@theo-cox  Okay makes sense. And I guess acceptance is to tick once it has been completed?

**Comment by nathenf** [comment]
We can use the great grasping, Liam just needs a few more days to reply to some comments.

**Comment by theo-cox** [comment]
Nah looks great @nathenf thanks!

**Comment by nathenf** [comment]
Liam is ready for this to go out, but would like someone to proofread the essay. @EilidhRoss1 could you do this? https://docs.google.com/document/d/1DQ8r4wQsIEJljhlCHCTJYQLAQ4MqLgZkNMYnJHd_AIk/edit

**Comment by EilidhRoss1** [comment]
@nathen or @lkavanagh30 could I please get access to that document?

**Comment by theo-cox** [comment]
@nathenf I think given we are likely/hoping to get lots more traffic to the site from the web3 project, I reckon we just add the singup now and can always retroactivley sort the welcome journey

**Comment by theo-cox** [comment]
@khalilcodes this is only for when you are fully back and ready to start work again, but could you please have a go at the above task: _Update website with email subscription forms including first name and email - popup window on the website linked to our mailchimp which comes up when people go to leave the site_

**Comment by nathenf** [comment]
Hey @khalilcodes I have made an email journey for the lead magnet and we're ready to go ahead with coding the submission forms into the website. Do you have some availability for a quick meeting this week?

**Comment by khalilcodes** [comment]
@nathenf Sure thing. Send me an invite and we can sync up on this.

**Comment by nathenf** [comment]
@khalilcodes what is your email, I will invite you to a meeting

**Comment by khalilcodes** [comment]
@nathenf khalilcodes@gmail.com

**Comment by nathenf** [comment]
@rufuspollock Khalil needs to access Wordpress to complete this task. Is there something you would like to do first before we go ahead with this?

**Comment by theo-cox** [comment]
@nathenf I have added Khalil to WP. @khalilcodes I'll whatsapp yo your temporary password

**Comment by rufuspollock** [comment]
@theo-cox can we add a job story (from the point of view of a user - not us) to this issue to clarify for @khalilcodes and I. Also are there 2 things here (also maybe one is a separate issue - i couldn't see)

- [ ] Have a sign-up form for our newsletter (preferably in pop-up form or similar on our blog etc)
- [ ] Have a "lead magnet" e.g. sign up to get X

Overall, it would be helpful to have the job stories (and maybe state up front research style the hypothesis we are testing e.g. that if we add a sign up form to our newsletter X people will use it per month ...)

**Comment by theo-cox** [comment]
@rufuspollock @khalilcodes job story and hypothesis done (sans numerical figure as this would have been completely arbitrary given my knowledge). @nathenf given this was your idea and issue originally please confirm this is ok.

P.s. its only implementing the signup for as per #43 that you and Khalil need to worry about. Lead magnet has been sorted by comms team, just needs final proofing I believe

**Comment by nathenf** [comment]
@theo-cox @rufuspollock @khalilcodes  to clarify, yes there are going to be two types of sign-up form on the website - the one from issue #43 which I suggest we put in the footer like this design [here](https://drive.google.com/file/d/16r1oAOoqjdNseeTajbAWVLvA6Acd8KvQ/view?usp=sharing). This will then be on every page and agree with above job story. 

Secondly we will have sign-up forms for the lead magnet. This will be placed as a banner [(see design)](https://drive.google.com/file/d/1sn-W-7iOfkDOjagfDeKcr1K4AU78U2kh/view?usp=sharing) [on there pages](https://docs.google.com/spreadsheets/d/1G0o93O0bSZ3SVIPOkT7pGsfJ9lhun-UPPW-c9PqEU7o/edit?usp=sharing) and also as a pop-up on exit [(see design)](https://drive.google.com/file/d/13XvaQLKyoMjINYBlvLDNM82zAAVVGC1P/view?usp=sharing). The button on the banner will lead to [this page where people can sign up](https://drive.google.com/file/d/1AuPaDZZbltDZpazmErnE7tvVjIE1yqoO/view?usp=sharing). 

Job Story  and hypothesis for lead magnet is above.

**Comment by khalilcodes** [comment]
@nathenf 
Some questions and requirements from tasks:

* *add ~~subscription form~~ banner (design above) to these [page locations]*
     - what is the required action for the ebook banners download now button ie., should they lead to the ebook landing page ?
* *Connect Mailchimp API to subscription forms*
     - Is the ebook form already setup in MailChimp ?
     - Need access to MailChimp for ebook form. Currently asks for sms or email verification during login.

**Comment by nathenf** [comment]
Hey @khalilcodes 

Yes the banner should lead to the landing page

Yes the email is ready to go, but the form is not. We can do email verification I believe, try to send it and I will see if I receive it.

**Comment by nathenf** [comment]
@khalilcodes I believe I don't have access to this email. @theo-cox can you get Khalil into Mailchimp?

**Comment by nathenf** [comment]
@khalilcodes 

This is the code for the form: 


<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7_dtp.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif;  width:600px;}
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://lifeitself.us12.list-manage.com/subscribe/post?u=f3b6955276a868159874a4e9a&amp;id=60854a9ee1" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Get the Ebook</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div hidden="true"><input type="hidden" name="tags" value="10325761"></div>
	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_f3b6955276a868159874a4e9a_60854a9ee1" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot">
                <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
                <p class="brandingLogo"><a href="http://eepurl.com/hSyVuT" title="Mailchimp - email marketing made easy and fun"><img src="https://eep.io/mc-cdn-images/template_images/branding_logo_text_dark_dtp.svg"></a></p>
            </div>
        </div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='MMERGE2';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>

**Comment by nathenf** [comment]
Hi @khalilcodes, so I've read up some more on GDPR and we do need to change the approach a little bit. 

1. We need to add a check box for people to receive regular updates via email. Only if they check this box can we add them to our mailing list. 
2. We need to make the check box add another tag to their contact "General" for example. 

In summary we will have two tags - "Great Grasping Lead" and "General" - Only the general can we send out newsletter to.

**Comment by khalilcodes** [comment]
As I was adding the form yesterday, I did see that the form has already been setup with the 'general' GDPR tag. 

To add/modify more GDPR tags I would need access to MailChimp, or the shared embedded code after it's been setup there accordingly.

**Comment by nathenf** [comment]
Hey @khalilcodes I have now updated the designs to be GDPR compliant and also added another task to create a page for the privacy policy and hyperlink this in the forms.

**Comment by khalilcodes** [comment]
Hi @nathenf  please review new updates for the following.

- [x] [Privacy policy page](https://lifeitself.us/privacy-policy/)
- [x] [Ebook landing page](https://lifeitself.us/free-ebook-the-great-grasping-by-liam-kavanagh/)
- [x] [Popup form](https://lifeitself.us/?elementor_library=ebook-popup-template)
- [x] [Subscription banner](https://lifeitself.us/?elementor_library=ebook-banner-section)

Also I have added the mailchimp code to forms but we need to test it, so let me know when you have tried submitting that. Thanks.

**Comment by theo-cox** [comment]
Hi @khalilcodes I have shifted mailchimp login to have security questions to verify ID. Answers are in the "notes" section of the Bitwarden entry for mailchimp. You should therefore be able to login - do let me know if its not the case

**Comment by khalilcodes** [comment]
Thanks @theo-cox will check it. 👍🏻

**Comment by nathenf** [comment]
@khalilcodes I am waiting to give you feedback, but unfortunately every time I check the website is down.

**Comment by nathenf** [comment]
@khalilcodes great work here are a few points for the page:

1. Can we change the slug for the ebook page to "Subscribe" instead
2. In the title "Why should you subscribe to our newsletter?", can you change our for "the Life Itself emails"
3. Can you make "Plus we send something extra to our subscribers when they sign-up" bold

For some reason the links to the pop-up and banner do not work for me. 

When attempting to sign up, it leads to this page: https://lifeitself.us12.list-manage.com/subscribe/post

**Comment by khalilcodes** [comment]
@nathenf. 

> *1. Can we change the slug for the ebook page to "Subscribe" instead*
> *2. In the title "Why should you subscribe to our newsletter?", can you change our for "the Life Itself emails"*
> *3. Can you make "Plus we send something extra to our subscribers when they sign-up" bold*

Done.

> *For some reason the links to the pop-up and banner do not work for me.*

what does it show ?

Form updated, so let's test it out.

**Comment by nathenf** [comment]
@khalilcodes it just takes me to the homepage. However, I am not logged into Wordpress perhaps this could be why? 

I tried to log in to Wordpress and got a 500 internal server error (nginx)

**Comment by nathenf** [comment]
Okay got it now @khalilcodes I tried to sign up through the pop-up but it didn't work for me.

**Comment by nathenf** [comment]
@khalilcodes the banner is great I just tweaked my own copy. Going to tweak something on the main page as well.

**Comment by nathenf** [comment]
@khalilcodes can we change the arrow on the ebook landing page to match the one on the life itself main homepage. It's slightly shorter and the grey colour rather than black

**Comment by nathenf** [comment]
@khalilcodes sorry for spamming, I could have put this all in one message... 

The subscribers from the form in the pop-up and landing page must be tagged "Great Grasping Lead" to initiate the welcome email.

**Comment by nathenf** [comment]
@khalilcodes where are we on this?
