### ISSUE TITLE
Promotion for Insight, Interbeing and Science Residency

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#21]
https://lifeitself.us/2022/02/07/insight-interbeing-and-science-may-2022/

What: A residency that allows us to collaboratively deepen our contemplative insight, particularly into interbeing, in a spirit of inquiry consistent with science. We can do this best with like-minded people, and will have time for remote working, too. We will look to refine practices together, and deepen our understanding of the potential and limitations of science for understanding spirituality.
When: 7 May - 28 May 2022 
Where: [Life Itself Praxis Hub, Bergerac, France](https://lifeitself.us/hubs/bergerac/) (near Bordeaux)
Who: anyone interested in insight, interbeing, and science.
Facilitators:  [Liam Kavanagh](https://lifeitself.us/people/) & Jamie Bristow

##Acceptance

- [ ] Residency Begins

##Tasks

- [x] Collect soundbite from @lkavanagh30 and create promo video for the Residency
- [ ] Add Promo video to Webpage via youtube and use this across social media and in the Newsletter
- [x] Have 20-30min interview with @lkavanagh30 around the topic of the residency to be published on Youtube and clipped for reels, shorts. 

@EilidhRoss1 @lkavanagh30 let's get some content created around this subject and brainstorm what we can create both pre-residency and during.

**Comment by EilidhRoss1** [comment]
@lkavanagh30 and I recorded a 25 min chat about the upcoming residency. it has been published to [Youtube](https://youtu.be/ojKz0eFnWMo). @nathenf is going to tweet about the video. Next task is to pull some shorter segments from the long video for social media

**Comment by nathenf** [comment]
Fixed - Residency ended
