### ISSUE TITLE
[Epic] T1 2022 Comms Drive

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#22]
## Description

We are aiming to supercharge our comms in 2022. This requires a bunch of actions to fulfill on our targets. Lets bang em out.

- [Comms Strategy for T1](https://docs.google.com/document/d/1eZBU49CwB1vjbES_Tm6kbR2Yhxmg1LtrIjbTE1wh2JA/edit#)
- [Content Mastersheet](https://docs.google.com/spreadsheets/d/1M3nqhszdQDYZeSHPttAevfsr0u9x_irLit9S-oUSzO0/edit#gid=1779022686)
- [Comms Analytics](https://docs.google.com/spreadsheets/d/1PLycC_qPr156OmGt35FpDsEwrxVZ5XIRrjdYOSaRToA/edit#gid=1970531174)
- [Yearly Calendar](https://docs.google.com/spreadsheets/d/1JBRbmd3T5HQgOxhZvZ0KpQnLgxlZLFEwEj1MCgN9Mtk/edit#gid=0)

## Acceptance

- [ ]  All comms infrastructure up and running as required
- [ ] We have a full content plan for the year including resources
- [ ] Everyone is clear on what they need to do to support comms efforts

## Tasks

- [ ] T1 planning **Theo proposal: We devote a good couple hours of T1 planning session to the below tasks**
     - [ ] Group session to bulk out the yearly calendar for 2022 (including days of relevance, e.g World Rewilding Day).
     - [ ] Group brainstorming session to begin planning online summit for 2022
     - [ ] Team effort to add short quotes, reflection questions and excerpts to the [LI Content Mastersheet](https://docs.google.com/spreadsheets/u/0/d/1M3nqhszdQDYZeSHPttAevfsr0u9x_irLit9S-oUSzO0/edit).
     - [ ] A team effort to collect more content (photos, videos, testimonials, etc.), ask @nathenf  for guidance: he can create a shot list for specific events.
- [ ] Mailchimp to be upgraded for a/b testing and email journeys. **@rufuspollock I think $21/month is worth it if we can significantly increase our functionality. Tagging here for visibility and to give opportunity for veto before I pull the trigger in Jan**
- [x] Brainstorm and implement a valuable lead magnet for newsletter sign-ups (a free offer in exchange for name and email). **There's discussion about whether this can be the contemplative activism book, or some collection of essays from the residency**
- [ ] Newsletter sign-up should be on every page of the website and must include at least first name and email. An unobtrusive pop-up form when people go to exit the website would also be great. **@rufuspollock can we get Khalil to do this when onboarded?**  
- [x] Newsletter template with correct formatting for ease of use. **@nathenf assigning you here**
- [ ] Welcome email journey created for new subscribers @nathenf 
- [x] Youtube video thumbnail template created @nathenf **Current one here: https://docs.google.com/presentation/d/1C-WRz8jeQ7EDOERDMNQvAXDpd4C6kCHJxYrjJGO8ewA/edit?usp=sharing**
- [x] Youtube profile and video captions optimised @nathenf 
- [x] Create a call to action to add to each Youtube video from now on @nathenf 
- [x] Create a SOP (standard operating procedure for new Youtube videos) @nathenf 
* [Recurring] Writers of new articles to complete the blog summary section in the [LI Content Mastersheet](https://docs.google.com/spreadsheets/u/0/d/1M3nqhszdQDYZeSHPttAevfsr0u9x_irLit9S-oUSzO0/edit) from now on. **@rufuspollock @lkavanagh30 @IljaMaiber to take note**

**Comment by nathenf** [comment]
Fixed - T1 results in and discussed in Comms meeting shifting overall comms strategy to #52
