### ISSUE TITLE
Promotion for Conscious Food Workshop

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#23]
What: 10-day residency to work and practice around the question of what is food today and how can we create an internal food system which sustains communities collectively and personally. Starts with a 5d intensive workshop led by Valérie Duvauchelle, a formal cook in the Zen tradition and pioneer in conscious food practices for Life Itself. [More info »](https://lifeitself.us/conscious-food-workshop/#overview)

When: 25 Apr 2022 to 4 May 2022 (workshop 26-29 Apr)

##Acceptance

- [ ] Workshop Begins

##Tasks

- [x] Write Questions for Valerie to answer for Video Promo
- [x] Create Promo Video
- [x] Upload video to webpage, youtube 
- [x] Share Promo on Twitter, IG & Facebook 
- [ ] Record "Podcast" with Valerie for Youtube

**Comment by theo-cox** [comment]
WONTFIX. This unlikely to go ahead anyway.

**Comment by nathenf** [comment]
Fixed - 9 people attending the workshop which Valerie is happy with. I believe zero came from our efforts except perhaps the promo video Valerie was able to share with her network. General lack of communication between residency lead and comms made for a poor collective effort to market. In addition, marketing to a French audience is difficult for us.
