### ISSUE TITLE
Optimize Qi Gong Article

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#24]
About 7% of our total website traffic comes from this one article, but 98% of visitors leave directly from this page. We need to optimize this page to capture their attention. 

I propose we create a free small ebook about Qi Gong, which will encourage users to type in their email and name. 

## Acceptance 

- [ ] Qi Gong eBook created
- [ ] Subscription form added to the article and customer journey created
- [ ] Add to Analytics - measure the conversion rate on a monthly basis (Out of people who visit the article, how many sign up for the ebook) 

## Tasks

- [ ] Plan and draft the eBook [using this document](https://docs.google.com/document/d/1Z6Bu5krSCmr-TMLzs14sHpFQOApoPqPY0YZBpUFVuDg/edit?usp=sharing)
- [ ] Make Cover for eBook
- [ ] Create Subscription form and email journey
- [ ] Adding tracking to [Analytics Spreadsheet](https://docs.google.com/spreadsheets/d/1PLycC_qPr156OmGt35FpDsEwrxVZ5XIRrjdYOSaRToA/edit#gid=1970531174)

**Comment by nathenf** [comment]
@EilidhRoss1 @theo-cox made the issue here to move forward with this task

**Comment by EilidhRoss1** [comment]
@nathenf [Qi Gong article](https://lifeitself.us/2020/05/12/qi-gong-the-eight-precious-exercises/) has been updated with a wee para on how Qi Gong relates to Life Itself and linking it to our Residencies page.

**Comment by theo-cox** [comment]
Thanks Eilidh! Do you want to have a go at closing the issue using the standard procedure to practice how to do it?

**Comment by nathenf** [comment]
@EilidhRoss1 perfect, it's great thank you!

**Comment by rufuspollock** [comment]
@nathenf a complementary (and initially simpler) suggestion could be

* We update our blog to have suggested articles (loads of plugins for this)
* Pop-up for newsletter subscribe with e.g. "subscribe to our newsletter and get more suggestions for wiser living like this" (?)

**Comment by nathenf** [comment]
@rufuspollock yes we should definitely do both of these, although the purpose of this is to get email sign-ups rather than send them directly to other articles. The latter is great and we are working to get lead magnets together (dramatically increases mail sign-up) and then we will roll this out across the website.

**Comment by theo-cox** [comment]
WONTFIX. We don't have capacity for this right now given other mission critical stuff.
