### ISSUE TITLE
Promotion of Community Gathering March 

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#25]
The community gathering begins on the 17th of March and we hope to completely fill it. 

Currently 5 attendees according to Tito is this correct @rufuspollock and what is the maximum number? 

## Acceptance

- [ ] Community Gathering begins on 17th March

## Tasks

- [x] Create script for Promo video - https://docs.google.com/document/d/1KM2TBxJdUt33R1oA_l4q5cd5gat1bsoOHfXeFh50GsU/edit
- [x] Do voiceover and create promo video - https://www.youtube.com/watch?v=5sshQYR6qRQ
- [x] Share promo via youtube, twitter, IG, Newsletter
- [x] Add promo to sign up page 
- [x] Schedule other posts on social media about the gathering  - I've scheduled 3 posts on Facebook and IG and a few on Twitter already.

**Comment by rufuspollock** [comment]
@nathenf my 2c but i'm not sure this event is one for the generic kind of promotion as it is more "friends and family" - good example to talk through on our next call to help clarify strategy.

**Comment by nathenf** [comment]
Fixed - Gathering Completed and Booked out
