### ISSUE TITLE
Evergreen Blog Content

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#26]
We need to have a look through all the blog posts and identify which ones will be useful as evergreen content, that is articles which provide value that is not time sensitive. Once we have identified them we will optimise them following the Blog SOP. This will all be added into the Content Mastersheet. 

##Key Documents

[Blog SOP](https://docs.google.com/document/d/1v6HgJEZINhnsxrHamHgZ26Fdc-ee8GWabb8zfbTBCYc/edit?usp=sharing)
[Content Mastersheet Blog Summaries](https://docs.google.com/spreadsheets/d/1M3nqhszdQDYZeSHPttAevfsr0u9x_irLit9S-oUSzO0/edit#gid=212260400)

##Acceptance

- [ ] Content Mastersheet Blog Summaries completed with all evergreen articles
- [ ] All evergreen articles optimised according to blog SOP
- [ ] All evergreen articles scheduled for first round of sharing on Facebook & Twitter

##Tasks

- [ ] Go through blog and identify evergreen articles and add the titles, author, link and publish date to Content Mastersheet
- [ ] Use Blog SOP to optimise the articles 
- [ ] Create feature images for each article
- [ ] Add a summary (can also just be the metadescription) to Content Mastersheet

**Comment by EilidhRoss1** [comment]
Have allocated an hour on Fridays to go through blog posts for evergreen material. Have been adding to [this sheet](https://docs.google.com/spreadsheets/d/1M3nqhszdQDYZeSHPttAevfsr0u9x_irLit9S-oUSzO0/edit#gid=1287501233).

**Comment by nathenf** [comment]
@EilidhRoss1 just wanted to flag #63 when going through and optimizing blogs let's avoid changing the slugs as this will break links if we have back links to these articles (as in external people linking to us).

**Comment by EilidhRoss1** [comment]
Thanks for flagging 👍

**Comment by nathenf** [comment]
FIXED - we have done this
