### ISSUE TITLE
Connecting Anchor to Distribution Channels

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#28]
So far we can distribute the podcast to Spotify and Anchor only. Definitely need to get it on Apple, Google and Overcast. Others are less important. 

## Acceptance

- [x] Available on all important platforms

## Tasks

- [x] Set up on Google Podcasts - just awaiting approval, but this is set up now. 
- [x] Set up on Apple - For this I need an Apple ID and password to use or I can set one up for Life Itself (I think this is possible)  @theo-cox ✅ **set up on [apple](https://podcasts.apple.com/gb/podcast/the-life-itself-podcast/id1618247766)**
- [x] Set up on Overcast - Must be submitted to apple first
- [ ] #41

**Comment by nathenf** [comment]
@theo-cox just need an apple ID to use here, can be yours or one for Life Itself (cannot find it Bitwarden).

**Comment by nathenf** [comment]
https://anchor.fm/life-itself/ - the 3 Web3 episodes that we created so far are up and the account has been optimized

**Comment by theo-cox** [comment]
> @theo-cox just need an apple ID to use here, can be yours or one for Life Itself (cannot find it Bitwarden).

I don't have one @nathenf so if you can set up one for LI that would be great

**Comment by nathenf** [comment]
@EilidhRoss1 I keep needing the code going to your phone, would you mind taking up the task of linking the podcast to Apple? You can just log in to Anchor and follow the podcast availability options, it should be pretty self explanatory. The log in for Apple is in Bit Warden as Apple ID. Once we're linked to Apple I can go ahead with the rest. Thanks!

**Comment by EilidhRoss1** [comment]
Having issues with the Apple ID. Keep on getting told by apple podcasts I can't continue until my apple ID is validated, which, from all the information I can find, it seems like it should be. When I get a moment I'll try get on the phone to apple, as haven't been able to get any help from any FAQs or question boards.

**Comment by EilidhRoss1** [comment]
Apple set up has been fixed and done: https://podcasts.apple.com/gb/podcast/the-life-itself-podcast/id1618247766

**Comment by nathenf** [comment]
It is automatically set up on Overcast as well now! Now we just want to add the RSS feed to the Web3 website. Can you do this @EilidhRoss1 or @rufuspollock? The RSS feed is linked above in the description

**Comment by rufuspollock** [comment]
@nathenf i wasn't planning to add an RSS to web3 site as not all conversations are web3 related ... However, we could add to life itself website. I'd suggest recording that as a separate task ... and i've taken the liberty of converting that checklist item to a task

**Comment by nathenf** [comment]
@rufuspollock definitely sounds reasonable. However, we can embed individual episodes on the Web3 site. I think if we are providing this extra form of content we should at least have direct links to it for people to navigate to. Last month we had about 230 plays on podcasts and although I can't find this information I can guarantee people who listen to the podcast will listen longer vs watch Youtube video. 

But yes definitely on the Life Itself website! Thanks for creating the task.

**Comment by nathenf** [comment]
fixed - Podcasts are available on Apple, Google, Spotify and Overcast. Adding to LI website has been moved to issue #41
