### ISSUE TITLE
Tweaking our design system

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#29]
When I am creating content for Life Itself, I want it to have a consistent design which supports our overall brand and objectives.

@nathenf has observed that currently our design system: 
a) Didn't have clear application to some of the content we're making (e.g. YouTube thumbnails) and
b) Didn't convey values like leadership, strength, rigour etc as much as we might like

He's created examples for use on our social media/YouTube etc which he thinks better convey these values: https://drive.google.com/drive/folders/1mZxfMdEs9C2GucOFSj05N_vzuWtoYj_3?usp=sharing

## Acceptance

- [ ] Nathen's examples have been reviewed
- [ ] We have agreed and implemented a newly tweaked design system

## Tasks

* [x] Summarize current design system **✅ 2022-03-08 see https://excalidraw.com/#room=b9581fedec7e9e11a9bf,SFtpYrW6uMxqq6TJMph3tg**
* [ ] Review suggested brand guideline iteration: https://drive.google.com/file/d/1d162KtAmO0kTN0kWE2SAiGFBUtFx2LPN/view?usp=sharing

**Comment by theo-cox** [comment]
@rufuspollock see here for design system and @nathenf's thoughts and examples

**Comment by rufuspollock** [comment]
@theo-cox @EilidhRoss1 @nathenf nathen's suggestions and folder of examples looks great. Let's chat asap to get something relatively finalized.

**Comment by rufuspollock** [comment]
Extensive analysis yesterday on design system and colors here: https://excalidraw.com/#room=b9581fedec7e9e11a9bf,SFtpYrW6uMxqq6TJMph3tg

Discussion today with nathen and eilidh leading to new "values" plus sense of direction - need to finish writing up (along lines of "alchemy of rigorous idealism")

**Comment by theo-cox** [comment]
Guys this is amazing! Love the direction we've gone in for the design system and looking forward to playing around implementing it. Well done all.

**Comment by theo-cox** [comment]
@nathenf can you add the link to the canva you created for us to review and discuss

**Comment by theo-cox** [comment]
@rufuspollock note @nathenf has created a suggested iteration of our brand guidelines: https://drive.google.com/file/d/1d162KtAmO0kTN0kWE2SAiGFBUtFx2LPN/view?usp=sharing 

This will be one of the things to discuss and review on our deep dive next week

**Comment by nathenf** [comment]
Not fixed - we are continuing mission on other issue #36 where iterations and main resources are.
