### ISSUE TITLE
New comms equipment for residencies

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#3]
We need proper equipment to capture photos and videos from residencies and events.

## Acceptance

- [ ] Equipment purchased and present in France
- [ ] Howto guide created and shared

## Tasks

- [ ] Find a phone to record **@nathenf recommended an iphone 11, and this appears to be a good deal: https://www.backmarket.co.uk/second-hand-iphone-11-64-gb-purple-unlocked/290062.html?shopping=gmc&gclid=CjwKCAiA55mPBhBOEiwANmzoQtlAqXt-VZFSLKP5T-4Kp9R1ILHynG8dYevQww-9Jt7NcP-T08R-QBoC0GcQAvD_BwE#?l=12**
- [ ] Find a mic **We used this for my old work and it worked well: https://www.amazon.co.uk/R%C3%98DE-VMML-Directional-Microphone-Devices/dp/B07F4MMLX5/ref=asc_df_B07F4MMLX5/?tag=googshopuk-21&linkCode=df0&hvadid=309952060520&hvpos=&hvnetw=g&hvrand=1421612318613389294&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9045623&hvtargid=pla-524350079665&th=1**
- [ ] Tripod stand **This seems suitable: https://www.amazon.co.uk/dp/B09MQG2ZMT/ref=sspa_dk_detail_3?psc=1p13NParams&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExNUNKQ0pPS0VLOE1TJmVuY3J5cHRlZElkPUEwMDEwNTIxWTRWU0RINEtKSEdDJmVuY3J5cHRlZEFkSWQ9QTA2NzQwMzIxMEU3T1FLV0I4SzU1JndpZGdldE5hbWU9c3BfZGV0YWlsMiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=**
- [ ] Light (?) **Open question whether we need this, but this would seem suitable https://www.amazon.co.uk/Diyife-Rechargeable-Brightness-Adjustment-Smartphone/dp/B07BML3WG3/ref=sr_1_1_sspa?crid=29VA25PZDOQHZ&keywords=phone+light+ring+rechargeable&qid=1642507184&s=electronics&sprefix=phone+light+ring+rechargable+%2Celectronics%2C124&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyUVlaNlM0NE5EUkpXJmVuY3J5cHRlZElkPUEwMzM1MTgxNFdUWlM5OFJZSzBVJmVuY3J5cHRlZEFkSWQ9QTA0NjY3NDQzMVkzSUlOR0FOQTAxJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==**

**Total cost on estimation remains under £400 GBP. Everything much more expensive on French sites so have avoided these.**

**Comment by theo-cox** [comment]
@nathenf could you review these and confirm they seem solid recommendations to you. @rufuspollock from prior conversations I believe I'm empowered to just pull the trigger on this when I'm happy but tagging here for visibility and to give an opportunity for input

**Comment by rufuspollock** [comment]
@theo-cox i've already provided an older iphone i just found.

**Comment by nathenf** [comment]
@rufuspollock what Iphone is it? There is a huge jump in quality from 9 to 10 which really makes a difference. 

@theo-cox I believe the link for the tripod is only the Tripod mount and not a tripod itself. This would be suitable: https://www.amazon.co.uk/YOTOCversion-Bluetooth-Cellphone-Compatible-Samsung/dp/B08RYJTT13/ref=sr_1_3?crid=1CWMAY339ALGR&keywords=phone+tripod&qid=1642563825&sprefix=phone+tripo%2Caps%2C292&sr=8-3

For audio the Lav mic is better for interviews as it reduces background noise: https://www.amazon.co.uk/R%C3%98DE-VMML-Directional-Microphone-Devices/dp/B00EO4A7L0/ref=asc_df_B07F4MMLX5/?tag=googshopuk-21&linkCode=df0&hvadid=309952060520&hvpos=&hvnetw=g&hvrand=1421612318613389294&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9045623&hvtargid=pla-524350079665&th=1 plus worth having an extension cable https://www.amazon.co.uk/Rode-Microphones-SC1-Cable/dp/B00WSNWFM8/ref=pd_bxgy_1/261-3771581-6061155?pd_rd_w=DFcQt&pf_rd_p=c7ea61ca-7168-47e3-9c8b-d84748f5b23c&pf_rd_r=HQZWBP0YPAREVS4WSZ2X&pd_rd_r=8f99a411-0883-4320-a24a-f6480c615911&pd_rd_wg=k0dNw&pd_rd_i=B00WSNWFM8&th=1

Light is less important at the moment, so maybe leave that for now. Can always find good natural light.

**Comment by rufuspollock** [comment]
@nathenf i think it is an iphone 9 but not sure. How do you tell?

**Comment by theo-cox** [comment]
@nathenf thanks re mic, and assuming we'll need a 3.5 jack to lighting adapter in that case. Re tripod, it's because we already have a tripod just not the adapter to fit a phone.

@rufuspollock there will be distinguishing physical features which should be ascertainable via googling. There wasn't actually a 9, it went from SE to X (ie 10). Big visible marker between these two is former has a physical home button, latter doesn't. X looks like this: https://www.google.com/search?q=iphone+X&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjZppr2w731AhWNQEEAHWQkDe4Q_AUoAnoECAIQBA&biw=1500&bih=899&dpr=2

**Comment by nathenf** [comment]
Oh yeah it wasn't called 9! I know Julie is using it now, so we can wait to see the quality before going ahead with the phone investment, she will be sending videos in the coming days. 

Good point about the lightning adaptor, maybe just go for the one that plugs directly in then. What do you think?

**Comment by theo-cox** [comment]
@rufuspollock nudge on this as it will determine next steps

**Comment by theo-cox** [comment]
@rufuspollock flagging for visibility that @nathenf has judged the camera and audio on our existing iphone to be of too low a quality to produce quality content. I'm therefore going to progress this as initially discussed.

**Comment by rufuspollock** [comment]
@theo-cox ok you know the comms budget - this will be about 5% of our annual budget ...

**Comment by theo-cox** [comment]
Yes, thanks. I may look into an iphone X rather than 11 to see if that saves, but I think investment in assets like this will do us well in the long term so it is worth it

**Comment by EilidhRoss1** [comment]
@theo-cox there are three options for iphone X: iphone X, XS and XR. 
* Iphone XS and X have have the same camera but the XS has new camera features such as Depth Control and advanced bokeh (relates to the quality of the blur in the out-of-focus portions of images). Video capabilities are also similar, but XS has cinematic video stabilization and stereo recording. Iphone XS also has dual sim capabilities. 
* Iphone XR was designed to be more affordable than the XS and X (but is still a newer phone than the X). While the iPhone X and XS have dual lenses, the XR has just one. The zoom on the XR isn't as powerful as on the other models, but it does have portrait mode with Depth Control and advanced bokeh, which XS has but the X does not.
* According to [Gazelle](https://buy.gazelle.com/pages/iphone-x-iphone-xs-iphone-xr), if you want the **best camera with the most photo and video features, go with the XS**. 

XS is a little more expensive on Back Market but only slightly. Here are the best deals I could find:
* [Iphone X](https://www.backmarket.co.uk/second-hand-iphone-x-64-gb-space-gray-unlocked/36833.html#l=12), 64GB £196.00 (down from £449.00)
* [Iphone XR](https://www.backmarket.co.uk/second-hand-iphone-xr-64-gb-white-unlocked/189925.html#l=12), 64GB £194.00 (down from 399.00)
* [Iphone XS](https://www.backmarket.co.uk/second-hand-iphone-xs-64-gb-space-gray-unlocked/178592.html#l=12), 64GB £209.00 (down from £649.00)

_From my research, if you're happy to splash out the extra £13-15, I'd advise going for the XS if you're wanting the best phone for capturing content. If you're not, it seems that the X would be the next best choice over the XR for mobile photography._

**Comment by nathenf** [comment]
@theo-cox did you pull the trigger on the mic already? I'm thinking again that perhaps getting a lavalier mic would be better, one that can fit to the phone but also a computer. Moving forward when we are recording calls via Zencastr we should aim to have high quality sound - so we would want to use the mic on the laptop.

**Comment by theo-cox** [comment]
No haven't copped anything yet. Could you find a well priced mic you think would work and then I can purchase all at once?

**Comment by nathenf** [comment]
@theo-cox here is what we should get mic wise. We need an adaptor for the Iphone, but at least we can then use the mic on the laptop as well when recording podcasts. I chose the double mic option as its only $15 more, but it will be handy to have if we want to conduct an interview with two people for example. Or an in-person podcast for that matter. 

https://www.amazon.com/Lavalier-Lapel-Microphones-Dual-Interview/dp/B07CHCSLVC/ref=cm_cr_arp_d_product_top?ie=UTF8

https://www.amazon.com/Cubilux-Lightning-Microphone-Monitoring-Compatible/dp/B08Q38FVQP/ref=sxin_13_pa_sp_search_thematic_sspa?crid=VLVU27BYX1H0&cv_ct_cx=lightning%2Bmicrophone%2Badapter&keywords=lightning%2Bmicrophone%2Badapter&pd_rd_i=B08Q38FVQP&pd_rd_r=524d0a41-9d5a-4a18-be42-8d9e9fd82834&pd_rd_w=IYIqo&pd_rd_wg=Aa3h6&pf_rd_p=54809c33-80a2-46df-9591-6ca7acea08f1&pf_rd_r=4G9EX9N8WB2FWNGE51X6&qid=1644992469&sprefix=lightning%2Bmicrophone%2Bad%2Caps%2C312&sr=1-2-a73d1c8c-2fd2-4f19-aa41-2df022bcb241-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExNEJHQUw2QlBOWkJSJmVuY3J5cHRlZElkPUEwMTM5MjI0MjcxVFg2Uk9MVjA4WSZlbmNyeXB0ZWRBZElkPUEwNjU4MzYwM1ZMMlVHU0wwNzhQUSZ3aWRnZXROYW1lPXNwX3NlYXJjaF90aGVtYXRpYyZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU&th=1

**Comment by theo-cox** [comment]
FIXED. We have purchased at a total cost of around £300.
