### ISSUE TITLE
Template Workflow for Web3 Conversation

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#30]
## Acceptance 

- [ ] Rufus and Stephen have been updated that conversation is ready to be published on YouTube and Anchor. 
- [ ] Page stub has been made and URL generated
- [ ] Conversation published on Youtube & Anchor
- [ ] Blog Post containing all content published
- [ ] Secondary Content and Direct links shared on Social Media

## Tasks

- [ ] Duplicate this Template and rename as the working title of the conversation
- [ ] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing)
- [ ] Source the video file and transcript from the conversation and add to folder
- [ ] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder.

- [ ] **Create Youtube video**
  - [ ] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
  - [ ] Edit the video file in Da Vinci Resolve:
    - [ ] Trim beginning and end, plus any sections of poor internet connection or other interruptions
    - [ ] Add thumbnail at the beginning of the video with a fade transition to the video
    - [ ] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute 
    - [ ] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
    - [ ] Increase the sound volume as much as possible without clipping the sound (you will notice because it will sound bad) 
  - [ ] Export as Video for Youtube
  - [ ] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to Web3 playlist, Add Language, Make License Creative Commons.
  - [ ] Notes from the conversation are on the webpage for that conversation.
    - [ ] Notes are complete, comprehensive and tidied
  - [ ] Inform Rufus and Guest that youtube video is ready to go.
  - [ ] Publish
  - [ ] Ensure Rufus & Guest tweet about video (for web3)
  - [ ] Share on Insta stories

- [ ] **Create Podcast**
  - [ ] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [ ] Add title & summary (incl page URL)
  - [ ] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [ ] Add season number and episode number
  - [ ] Publish
  - [ ] Inform Rufus and Stephen (for web3)
  - [ ] Share on Insta stories

- [ ] **Create Twitter Secondary Content**
  - [ ] Cut the video excerpts from the main video and leave all the clips in one timeline
         - [ ] Export just the audio
         - [ ] Upload Audio to Otter.ai to create srt file (srt file settings: no more than 1 line and 60 letters per line) - make sure that the speech from each clip is correctly separated in Otter.ai
         - [ ] Upload the srt file to the project 
         - [ ] Crop top and bottom of video - add title to top and subtitles at the bottom
  - [ ] Create Quote posts using [this template](https://www.canva.com/design/DAE-ett42vU/63HsI5cGixlZ6cFQd09zCg/edit)
  - [ ] Add all content to the folder that has been created 

- [ ] **Create Blog Post**
  - [ ] Create a blog post beginning with the summary then embed the video, the podcast and include the transcript
  - [ ] Add the relevant quotes and video excerpts (Twitter format) as images between the transcript

- [ ] Compile all the information in the [Web3 Spreadsheet](https://docs.google.com/spreadsheets/d/12Yh1kuxH4uoposLUJsJifM2W_zixkAhlc7QgcKavfls/edit#gid=2377395)

- [ ] Send email to "Web3" mailing list on Mailchimp

**Once blog is complete we can schedule content on Twitter**

**Comment by nathenf** [comment]
@EilidhRoss1 here is the first run through. Let me know if you have a questions. Let's schedule a call next week for the proper handover

**Comment by nathenf** [comment]
@EilidhRoss1 i've adding creating a content and chapters on youtube like this: https://www.youtube.com/watch?v=pvkTC2xIbeY it was requested in a previous video and I believe will improve the watch time.

**Comment by nathenf** [comment]
@EilidhRoss1 also updated for email sending task

**Comment by nathenf** [comment]
FIXED - Web3 podcast is now closed. Workflow is stored for reference here: https://docs.google.com/document/d/14-Cm_MEzTpITbTmPivRKp-o33OYDew1jNV4pT4JHAWM/edit#
