### ISSUE TITLE
Stephen and Rufus episode 4

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/comms#31]
## Acceptance 

- [ ] Conversation published on Youtube & Anchor
- [ ] Blog Post containing all content published
- [ ] Secondary Content and Direct links shared on Social Media

## Tasks

- [x] Duplicate this Template and rename as the working title of the conversation
- [ ] Create a new folder for the conversation here: TBC **we need to link up on file storage**
- [ ] Source the video file and transcript from the conversation and add to folder
- [ ] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes. Add this to folder.

- [ ] **Create Youtube video**
  - [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE0jpVGmYc/ZqHVHrVNiniCS83nr4JjfQ/view?utm_content=DAE0jpVGmYc&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview).
  - [x] Edit the video file in VN Editor:
  - [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
  - [x] Add thumbnail at the beginning of the video with a fade transition to the video
  - [x] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute 
  - [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
  - [x] Increase the sound volume as much as possible without clipping the sound (you will notice because it will sound bad) 
  - [x] Export as Video and also Audio only
  - [x] Upload to Youtube: Add title, thumbnail, summary, add to Web3 playlist, Add Language, Make License Creative Commons.

- [x] **Create Podcast**
  - [x] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [x] Add title & summary
  - [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE54jmAtvg/WrhRg3ZXky9HGlM_wSFvDA/view?utm_content=DAE54jmAtvg&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [x] Add season number and episode number

- [ ] **Create Secondary Content**
  - [ ] Cut the video excerpts from the main video
  - [ ] For reels, change the video for to 4:5 and the Canvas to 9:16 - [Add this as a the background](https://www.canva.com/design/DAE5tHBDipU/1xYtzxMaw9I6qt6EWnYJPA/view?utm_content=DAE5tHBDipU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [ ] Reduce video saturation to -100
  - [ ] Write subtitles overlay to go above the video on the background
  - [ ] Create Reel Cover using [this template](https://www.canva.com/design/DAE5tHBDipU/1xYtzxMaw9I6qt6EWnYJPA/view?utm_content=DAE5tHBDipU&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [ ] For Twitter Keep the video excerpt as 16:9 format and add subtitles to the top of the video
  - [ ] Create Quote posts using [this template](https://www.canva.com/design/DAE55uh2UYk/ej7oANpJqsO5-0rWq2at1Q/view?utm_content=DAE55uh2UYk&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)
  - [ ] Add all content to the folder that has been created 

- [ ] **Create Blog Post**
  - [ ] Create a blog post beginning with the summary then embed the video, the podcast and include the transcript
  - [ ] Add the relevant quotes and video excerpts (Twitter format) as images between the transcript

- [ ] Compile all the information in the [Web3 Spreadsheet](https://docs.google.com/spreadsheets/d/12Yh1kuxH4uoposLUJsJifM2W_zixkAhlc7QgcKavfls/edit#gid=2377395)

**Once blog is complete we can schedule content on Twitter, FB and IG**

**Comment by nathenf** [comment]
@EilidhRoss1 can you add this to the comms planning board and update progress. Would be good to organise everything into the correct folder on drive as well. :) Thank you!
