### ISSUE TITLE
Shift all templates, files and branding to LI Canva Profile

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#33]
##Acceptance

- [x] Canva is organised and prepared for efficient content creation

##Tasks

- [x] Add Branding to Canva
- [x] Create folders for images and graphics 
- [x] Name and organise all templates

**Comment by nathenf** [comment]
fixed - Canva files shifted and sorted from my account. We are now good to go I will update you @EilidhRoss1 on file sorting and efficient use of Canva
