### ISSUE TITLE
Content Strategy and template for IG Stories

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#34]
##Acceptance 

- [ ] Strategy and templates created
- [ ] First use of templates 

##Tasks

- [ ] Add to LI Content Mastersheet
- [ ] Create graphics
