### ISSUE TITLE
Quick Wordpress Task 

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#35]
##Acceptance

- [ ] Residencies Page and Drop down menu fixed

##Tasks

- [ ] Remove old residencies from the drop down menu
- [ ] Add Insight Interbeing and Science to main residency page

**Comment by nathenf** [comment]
@EilidhRoss1 I think this is still to do. We need to update the drop down menu: Remove, the old conscious food and Eco-Spirituality and add the latest, emergent dialogue below insight and interbeing. https://lifeitself.us/sympoiesis/7-emergent-dialogue-residency-june-2022/ 

Also I think we should switch the page around, showing the residencies that have already been completed at the top of the page is highly ineffective. Either we remove them or have a past Sympoeisis section at the bottom, then have the upcoming ones right at the top instead. If @theo-cox and you agree, let's action this.

**Comment by EilidhRoss1** [comment]
Yes, sorry the interbeing residency had been added to the drop down but the old stuff hasn't been cleared off and the newest residency hasn't been added on. and yes I 100% agree about re-ordering that page

**Comment by theo-cox** [comment]
FIXED. Menu adjusted. Agree on the comment re residencies page @nathenf @EilidhRoss1 so let's do that. Also a prime example of something you definitely don't need my sign-off to do!
