### ISSUE TITLE
Optimizing Linked In

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#37]
Consider Linkedin to be the outward facing lead generator for labs. Everything else that Life Itself does will be sidelined here and a majority focus on targeting organizations, policy makers, etc who need out help. 

Question for you @theo-cox, what clients have we already had and what were their pain points? Conscisely what problem can we solve for our audience.

**Key terms for use**: #systemsdesign #systemthinking #dataanalysis #networkmapping give me more...

**What content do we have for here**
- Case Studies
- White Papers
- Articles on Collaborations with GIZ, ETC. 
- Ecosystem mapping techniques and theory
- How do we provide value to help our audience address their pain points?
- Polls around the pain points of our target clients
- Video Excerpts from Youtube 

##Acceptance

- [ ] LinkedIn Optimized
- [ ] Content Strategy Created
- [ ] Posting Begins

#Tasks 

- [ ] Research Hashtags 
- [ ] Create Featured Group for Ecosystem Mapping
- [ ] Update Banner
- [ ] Update Profile to be more focussed on the labs work
- [ ] Add Product for booking consultation
- [ ] Change button to Contact Us 
- [ ] Select Specialities
- [ ] Update description to include what we do, who we have worked for and where we are featured. 
- [ ] Write up case studies with references from previous clients

**Comment by theo-cox** [comment]
@nathenf flagging this is acknowledged, but am putting on backlog to prioritise doing professional content for Labs as this is what we'll be sharing on LinkedIn. Maybe we even have a Labs LinkedIn as it's own thing...?

**Comment by nathenf** [comment]
@theo-cox I think in general we just treat Linkedin as the space for Labs so no need to create a different Linkedin. Let us discuss in the next comms meeting
