### ISSUE TITLE
Promo for Emergent Dialogue Residency

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#39]
Sympoiesis 7: Emergent Dialogue – 6 Jun – 3 Jul 2022

##Acceptance

- [ ]  Residency Begins

##Tasks

- [ ] Collect soundbite from Elizabeth Debold and create promo video for the Residency
- [ ]  Add Promo video to Webpage via youtube and use this across social media and in the Newsletter
- [ ] Have 20-30min interview with Elizabeth and Thomas around the topic of the residency to be published on Youtube and clipped for reels, shorts.
- [ ] Build content into social media schedules for entire month of April

**Comment by nathenf** [comment]
Not Fixed - This residency is postponed until further notice
