### ISSUE TITLE
Podcast series

### ISSUE THREAD

**Issue by theo-cox** [life-itself/comms#4]
[Planning & Strategy Document](https://docs.google.com/document/d/1PbygQiZNECMJ3ZxGbLP3ZcMhZR4BLoJg0TBcpdZR2yA/edit?usp=sharing) - UNDER CONSTRUCTION

We floated the idea in https://github.com/life-itself/labs/issues/17 but these were somewhat undirected, and the series hasn't really taken off. I'm therefore forking the podcast bit here, and suggest we keep the former issue just as an Imaginary Society backlog.

@nathenf has suggested a podcast series will be gamechanging for our content and web presence, and I see it as an area we could add a lot of value to the space. There are two (non-mutually exclusive) directions we could go:

1) Longform discussions with selected residency participants (we have lots of interesting people coming through, especially when we include co-hosts such as Karl and Rupert).

2) A podcast series as part of the ecosystem mapping project, where we interview different people/orgs from across "the space"

We can do both, but my suggestion would be weighting heavily towards 2 as this is the highest value add both to our projects and to the wider ecosystem imo. 

[Zencastr](https://zencastr.com/dashboard) is set up and there is a free version we can use to begin with. At most it will cost $20 a month, which will be a good investment as we get into the swing of things. 

[Anchor](https://anchor.fm/) is a free podcast hosting platform we can use. 

## Acceptance

- [ ] Infrastructure and plan for our podcast series in place
- [x] First episode recorded and shared

## Tasks

- [ ] Planning and infrastructure
    - [x] Create Workflow Issue Template for GitHub
    - [x] Tools list and cost **@nathenf thinks we just need https://zencastr.com/**
    - [ ] Time budget
    - [ ] Role allocation esp. who's going to engage in the conversations
    - [ ] Overall budget for project
    - [ ] Planning guests and creating backlog
    - [ ] Other infrastructure creation e.g. image templates, hosting accounts, standard intro recording, standard intro email template etc **might be able to adapt this for email: https://docs.google.com/document/d/1k2apKGyhCOd5ppKllYcb4nbZ4wZAzWRzxPxatlmM3T8/edit**
- [x] Engagement
    - [x] Contacting first 5 guests
    - [x] Booking in dates
- [x] Ep. 1 recording
- [x] Ep. 1 processing and sharing 
- [x] Ep. 1 promo

**Comment by theo-cox** [comment]
@rufuspollock @nathenf flagging here for visibility. This is something I will be taking forward unless overruled, and we can discuss in our next strategy meeting the point on roles and other bits.

**Comment by nathenf** [comment]
Yep I agree going for two. When we spoke I meant only the residency hosts not the participants, better to go after the thought leaders. However, if we go ahead with this soon I would recommend we begin with Rupert and use this to promote the residency.

**Comment by nathenf** [comment]
https://riverside.fm/pricing

**Comment by rufuspollock** [comment]
@theo-cox minor issue management point - i don't think we want to fork off and leave another one (we end up drowning in issues). couldn't we just move the old issue here and repurpose i.e. https://github.com/life-itself/labs/issues/17

As an aside: these kind of implementation thing is up to you and Nathen ... though it would be good to finalize the strategy doc to make sense of how this related ...

**Comment by nathenf** [comment]
FIXED - podcast is up and running with post-interview procedure in place
