### ISSUE TITLE
Create Comms/Basic Web FAQ Spreadsheet

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#48]
I think it would be really useful to have an ongoing FAQ sheet for simple answers (can also link to youtube videos) for questions regarding comms and basic website updating. For example, "What dimensions should an image be on Twitter?" or "How do I add timestamps to a Youtube video". 

The intention is that this will improve our workflow as we can first turn to the FAQs before needing advice elsewhere. 

## Acceptance

- [ ] The spreadsheet is created and is starting to be used/added to

## Tasks

- [x] Brainstorm Categories (Youtube, Twitter, Website, etc.) 
- [x] Brainstorm questions to answer
- [X] Create spreadsheet - https://docs.google.com/spreadsheets/d/1CFXX06GhUWDtUpplvg2L5OBwn_A-R23VxMXYvNN41uA/edit#gid=0
- [ ] Inform everyone of the spreadsheet

**Comment by nathenf** [comment]
@theo-cox @rufuspollock - I just came up with this idea but wanted to run it by you first before taking action. I think it could be a really useful resource, especially for creating consistency with dimensions, file sizes, etc. Let me know your thoughts.

**Comment by theo-cox** [comment]
I think the more stuff we can capture via standard process the better as it reduces the time you spend on answering questions and builds in resilience if we need to do stuff without you. So I would say do it - and probs not worth waiting on a response to Rufus to get going, especially given this is your domain to make the call.

**Comment by nathenf** [comment]
FIXED - the spreadsheet exists, but there has not been so many concrete actions to include thus far https://docs.google.com/spreadsheets/d/1CFXX06GhUWDtUpplvg2L5OBwn_A-R23VxMXYvNN41uA/edit?usp=share_link
