### ISSUE TITLE
[Epic] Life Itself Website Restructure

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#49]
**Job Story** 
When people come to our website they want to be able to easily navigate to our most recent work and initiatives. They want to be taken on a journey which encourages them to explore the whole website or at least find a number of things that they are interested in. From the homepage they should instantly get a feel for what Life Itself is and what it can offer. They also want to easily be able to return and find new content and news. 

**Hypothesis**
What we would be aiming to observe is an increased number of returning users (because the usability of the website encourages more people to return), a decrease in bounce rate, an increase in session duration and number of pages per session. This should steadily increase our number of users as we gain more returning users. 

**Resources**
[Document for layout](https://docs.google.com/document/d/1y_CG4rdWO7IvCEsMux9lVRO_ko_BTHWAZetTe9-CD9I/edit?usp=sharing) 

##Acceptance

- [ ] New website structure implemented and monitored

##Tasks

- [ ] @nathenf to create first draft of homepage 
- [x] @nathenf to create header menu
- [ ] @nathenf to create footer
- [ ] Create residency testimonials page
- [ ] Create what is Labs page
- [ ] Create what is Spaces page
- [ ] Create past initiative page
- [ ] Create featured in page
- [ ] Create main spaces page
- [ ] Create press enquiries page
- [ ] Improve utility of the blog

**Comment by nathenf** [comment]
NOT FIXED - Merged with https://github.com/life-itself/community/issues/149
