### ISSUE TITLE
Clean Up Database Spreadsheet & Build Out

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#5]
Apart from the people tab of the network database, it is quite empty and untidy. This can be cleaned up and slowly built out with contacts such as publications, podcasts, projects etc. 

https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1139431819

## Acceptance

- [ ] @theo-cox confirms that the spreadsheet is clean and useful
- [x] Lists are built out with at least 10 leads in each section

## Tasks

- [x] Clean up spreadsheet
- [x] Research podcasts to be on
- [x] Cross Reference with other DB Spreadsheet - for now I have added the other tab to this spreadsheet as organizations. I think cross referencing is not a good use of my time right now

**Comment by nathenf** [comment]
@theo-cox is this already merged into the database? It is probably quite a task, but if it isn't it might be worth doing? https://docs.google.com/spreadsheets/d/1QJpTHWr9RKZGFaKjIR6itpQqQlGJNfXmoR8nFw-72EU/edit#gid=0

**Comment by theo-cox** [comment]
I'm not sure as this was before my time. If you copy the tab to the main CRM sheet then I think you can cross reference and see? From a first pass think there's some overlap but likely some stuff that's also not on there, but don't quote me on that

**Comment by nathenf** [comment]
@theo-cox I have just merged the database into this one so everything is in one place. Ready to Close this now if you are good to

**Comment by theo-cox** [comment]
Thanks. Yes go ahead and we can discuss next steps for the DB in our meeting next week.

**Comment by nathenf** [comment]
fixed - this is done
