### ISSUE TITLE
[Epic] Q2 2022 Comms Mission & Goals

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#52]
In Q1 we were able to establish a great content workflow and begin steady growth on Youtube, Twitter & Podcast with a focus on Web3 content. 

This quarter we want to expand the proven content strategy to encompass more spaces and LI at large. We also want boost levels of engagement with our audience. 

Engage with ecosystem mapping: We want people to at least visit the site and spend time exploring it. We want organisations to submit themselves to the map. We want other websites in the space to list this as a resource (backlinks).

**RETROSPECTIVE**

The goals and outcomes were set out after the end of T1 rather than at the start of Q2 and the outcomes were quite aspirational for the month and a half until the end of the Quarter. However, with the trajectory we were on with Web3 it felt like we would easily be able to achieve these KPIs. 

Web3 slowed down in the last month of Q2 and we were starting from scratch with the Social Transformation podcast series.  Furthermore, the managerial shift of Praxis means we did very little comms work around residencies. Labs website was complete in mid Q2, but we have yet to pull the trigger on Labs marketing. 

Despite all this Theo and other members have experienced positive feedback about where Life Itself is going and people are noticing that LI is moving from strength to strength. We have made great steps since the beginning of Q1 and have strong consistent growth. 

##Acceptance

- [ ] KPIs reached
- [ ] Worked effectively towards suggested outcomes
- [ ] Content Creation SOP used for Spaces and Mapping project 
- [ ] Labs marketing strategy developed 

##Outcomes

- [ ] Increased awareness of Life Itself as a thought leader in Tech & Culture as measured by levels of engagement with our primary content (YT & Podcast) 
- [ ] Residencies fully booked & other events well attended measured by feedback form filled out by residents
- [ ] Increased requests to hire Labs or collaborate with Spaces

##KPIs

- [ ] Twitter Followers = 1000 - 926
- [ ] Youtube Subs = 600 - 377
- [ ] Podcast Listens = 4000 - 3000
- [ ] Newsletter Open rate = 50% - 40%
- [ ] Monthly Web Users = 2400 - 2800

##Tasks

- [ ] Implement and Test lead magnet, welcome newsletter #2 & #43 - NOT FIXED, waiting on final push from Tech Team
- [ ] Improve UX/UI of LI Website #49 - Ongoing
- [ ] Complete Blog summaries for evergreen content #26 - Will be complete early Q3
- [ ] Build out marketing strategy for Labs #56 - NOT FIXED
- [ ] Optimizing and beginning to use Linkedin for Labs #37  - NOT FIXED
- [X] Do 5-10 interviews with Mapping Organisations #53 - FIXED & Underway
- [ ] PR Drive #12 and #13 - NOT FIXED

**Comment by nathenf** [comment]
@theo-cox @EilidhRoss1 added what I think our outcomes from the comms effort should be, please add your thoughts as well

**Comment by nathenf** [comment]
FIXED - The goals and outcomes were set out after the end of T1 rather than at the start of Q2 and the outcomes were quite aspirational for the month and a half until the end of the Quarter. However, with the trajectory we were on with Web3 it felt like we would easily be able to achieve these KPIs. 

Web3 slowed down in the last month of Q2 and we were starting from scratch with the Social Transformation podcast series.  Furthermore, the managerial shift of Praxis means we did very little comms work around residencies. Labs website was complete in mid Q2, but we have yet to pull the trigger on Labs marketing. 

Despite all this Theo and other members have experienced positive feedback about where Life Itself is going and people are noticing that LI is moving from strength to strength. We have made great steps since the beginning of Q1 and have strong consistent growth.
