### ISSUE TITLE
Exploring Social Transformation Podcast Plan

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#53]
**Job Story**
Learning about the organisations with the Metamodern Ecosystem helps me become more informed about what change is happening, how I can support, or where I can fit in. I can also take inspiration from these conversations and it helps me be inspired by Life Itself and find other ways to interact with Life Itself. 

**Resources**
[Ecosystem Mapping Talking Points](https://docs.google.com/document/d/1VlqDPGlOg3gUa2eOkSbKEe4FhwN1MKgyI-PC6WQKmhE/edit )

##Acceptance

- [x] First episode complete and set up then with consistent output of conversations. 

##Tasks 

- [x] Decide who we should interview and who will interview who
- [x] Tweak templates for YT & Podcast to reflect different content

**People to Interview from Ecosystem Map**

- Rich DB, Enspiral & The Hum https://twitter.com/RichDecibels 
- Anna Shafner, Emerge https://twitter.com/AKSchaffner
- Karl Steyaert https://twitter.com/karlsteyaert
- Jamies Bristow, Mindful Initiative https://twitter.com/JamieBristow
- Rob Hopkins, Transition Movement https://twitter.com/robintransition
- Soren Gordhamer, Wisdom 2.0 https://twitter.com/SorenG
- Alexander Beiner, Rebel Wisdom https://twitter.com/AlexanderBeiner
- Krista Tippet, https://twitter.com/KristaTippett
- Nick Spencer, Theos Think Tank https://twitter.com/theosnick
- Mind & Life Institute https://twitter.com/mindandlife
- Otto Scharmer, Presencing Institute https://twitter.com/ottoscharmer1
- Satish Kumar, Schumacher College & Resurgence Magazine https://twitter.com/SchumacherColl
- London Mindful https://twitter.com/LondonMindful
- Indy Johar, Dark Matter Labs https://twitter.com/indy_johar
- Psychedelic Society https://twitter.com/PsychedelicsUK

**Comment by nathenf** [comment]
@EilidhRoss1 this is a list of people we might want to interview from mapping metamodern based on their influence and following. Take a peek through and see if any take your fancy. I'm very keen to take Rob Hopkins and would love to speak with Satish Kumar as well but otherwise I know very little about these people

**Comment by nathenf** [comment]
@theo-cox for visibility and your thoughts on this list. Anyone we can access easy etc.

**Comment by nathenf** [comment]
@EilidhRoss1 @theo-cox I've added a document for talking points can you take a look and add your thoughts. Currently very simple

**Comment by nathenf** [comment]
Fixed - This is now in Process

**Comment by nathenf** [comment]
FIXED - Exploring Social Transformation Podcast Series is now closed. I have moved the interview list to https://docs.google.com/document/d/1HFPtTFH03Hxm6H-wy2xdX-kylnltunoXga7p7xTwi3k/edit?usp=share_link
