### ISSUE TITLE
[Epic] Instagram relaunch

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#54]
**Situation:** Even after posting and engaging on current Instagram we have seen poor adoption and engagement. 

**Complication:** The Instagram algorithm has restricted our opportunities for growth due to our engagement rate and potentially inactive followers. 

**Question:** How do we increase our engagement such that our posts are seen and we can steadily grow our account? 

**Hypothesis:** Restarting our Instagram page will give us the reset needed to have a decent engagement rate and then we can grow from a good place

##Acceptance

- [ ] Instagram relaunched 
- [ ] Steady engagement and posting 
- [ ] Story and posting strategy implemented 

##Tasks

- [ ] Change name of current account and create new account with @forlifeitself
- [ ] Optimize 
- [ ] Have 1 month of content ready prior to opening new account
- [ ] Engage with followers on current account to move over if they want to continue following (and engaging)
- [ ] Iterate content strategy for posts & stories #34

**Comment by nathenf** [comment]
NOT FIXED - not a priority and will likely not do this in the future
