### ISSUE TITLE
2022 Online Summit Ideas

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#55]
**Job Story:** I am looking for a place to get an overview of the metamodern ecosystem and learn about what is out there and network with other people in the space. This should be a focussed space where I can get a lot of information condensed together that gives me the opportunity to explore further as I want. 

**Hypothesis:** A virtual summit hosted by Life Itself will be a great way to increase brand visibility, collect email addresses and upsell our products (residencies, hire us, etc.). In our mission to be a space for thought leadership we would be bringing together the great minds in our network and showing our ability to manage large community events online for the benefit of our mission. 

##Acceptance

- [ ] Idea for summit confirmed
- [ ] Preliminary proposal of resources needed, etc. complete

##Tasks

- [ ] Learn how to structure effective online summits
