### ISSUE TITLE
Template for Social Transformation Conversation

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#60]
## Acceptance 

- [ ] Conversation published on Youtube & Anchor
- [ ] Blog Post containing all content published
- [ ] Secondary Content and Direct links shared on Social Media

## Tasks

- [ ] Duplicate this Template and rename as the working title of the conversation
- [ ] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing)
- [ ] Source the video file and transcript from the conversation and add to folder
- [ ] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder.

- [ ] **Create Youtube video**
  - [ ] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
  - [ ] Edit the video file in Da Vinci Resolve:
    - [ ] Trim beginning and end, plus any sections of poor internet connection or other interruptions
    - [ ] Add thumbnail at the beginning of the video with a fade transition to the video
    - [ ] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute 
    - [ ] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
    - [ ] Increase the sound volume as much as possible without clipping the sound (you will notice because it will sound bad) 
  - [ ] Export as Video for Youtube
  - [ ] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to Exploring Social Transformation playlist, Add Language, Make License Creative Commons.
  - [ ] Notes from the conversation are on the webpage for that conversation.
    - [ ] Notes are complete, comprehensive and tidied
  - [ ] Inform Guest that youtube video is ready to go.
  - [ ] Publish
  - [ ] Ensure Guest tweet about video
  - [ ] Share on Insta stories

- [ ] **Create Podcast**
  - [ ] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [ ] Add title & summary (incl page URL)
  - [ ] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [ ] Add season number and episode number
  - [ ] Publish
  - [ ] Share on Insta stories

- [ ] **Create Twitter Secondary Content**
  - [ ] Cut the video excerpts from the main video and leave all the clips in one timeline
         - [ ] Export just the audio
         - [ ] Upload Audio to Otter.ai to create srt file (srt file settings: no more than 1 line and 60 letters per line) - make sure that the speech from each clip is correctly separated in Otter.ai
         - [ ] Upload the srt file to the project 
         - [ ] Crop top and bottom of video - add title to top and subtitles at the bottom
  - [ ] Create Quote posts using [this template](https://www.canva.com/design/DAE-ett42vU/63HsI5cGixlZ6cFQd09zCg/edit)
  - [ ] Add all content to the folder that has been created 

- [ ] **Create Twitter Secondary Content**
  - [ ] Use the same clips from Twitter and reformat for Reels

- [ ] **Create Blog Post**
  - [ ] Create a blog post beginning with the summary then embed the video, the podcast and include the transcript
  - [ ] Add the relevant quotes and video excerpts (Twitter format) as images between the transcript

- [ ] **Send email out to Life Itself General Audience**

**Once blog is complete we can schedule content on Twitter, Instagram**

**Comment by nathenf** [comment]
@EilidhRoss1 I have separated out this template from the Web3 one to reflect the nuances between the two. Feel free to optimize this to include the instagram workflow

**Comment by nathenf** [comment]
@EilidhRoss1 updated to include the email task

**Comment by nathenf** [comment]
FIXED - used for the series, this workflow is now saved here: https://docs.google.com/document/d/1dkW2rn3hBcKE2UvM4qElFQ8cja3DiUVsZVn0SL4DlNA/edit#heading=h.nfptqfxw5l4j
