### ISSUE TITLE
[EPIC] Email Marketing Make-Over

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#61]
**Situation**: Our open rate has been declining over the last months. Eilidh noticed that the newsletter has been going to her promotions tab rather than the main inbox on gmail. This is likely happening for others too.

With our output being a monthly newsletter, this type of email screams promotion (algorithmically) for a number of reasons: 
1. Lots of links 
2. Lots of images
3. Language like "Apply Now" at multiple points

**Complication**: Lower open rates means that less people are viewing our content and therefore we are having less impact via our thought leadership and we are getting less leads for residencies. 

**Question**: How to we increase open rate and avoid being put in the promotions inbox? 

**Hypothesis**: Firstly, we should send more simple emails, more often with just one link per email. Let's get rid of images all together and just have text. 

Secondly, let us ask our current audience what they want to receive updates about. For example, many of our subscribers may not be interested to hear about Web3. 

Thirdly, we do not include peoples names: This type of personalisation can increase the chances of getting the email into the inbox. We can also put a name for one of us signing off. More like a personal email from one to another. 

##Acceptance

- [x] Transition to new email strategy
- [x] Monitor Improvements

##Tasks

- [x] Go through subscriber list and try to add first names inferred from the email address (only add if we can be 100% sure) 
- [x] Clean up current tags (do we need them, can we change them?) - maybe a tag for residencies Alumni would be useful
- [ ] Send a survey to our subscribers to ask if they want to receive updates about Web3 - Not Fixed, since we will be sending questionnaire shortly anyway
- [x] Create new email template
- [x] Test new email strategy to see if it works

**Comment by theo-cox** [comment]
This looks like a great analysis @nathenf . Thanks for leadership on this.

**Comment by nathenf** [comment]
What if we write our monthly digest as a blog post and then we can write a small simple email with one link + drive traffic to the website.

**Comment by nathenf** [comment]
FIXED - Analytics and iterations ongoing, but shift has happened. So far our open rate has levelled around 43.5%, but with more regular emails, the amount of people engaging with our content is higher. This is a great step in the right direction and we continue to improve.
