### ISSUE TITLE
Engagement drive for Twitter & Instagram

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#65]
Situation: Our Instagram and Twitter continues to grow in followers, but engagement remains relatively low. 

Complication: Lack of engagement means we put time into creating content which isn't seen. 

Question: How can we improve engagement?

Hypothesis: By having a focussed and consistent engagement strategy we can improve overall engagement and grow the brand extensively. 

##Acceptance

- [ ] Engagement strategy created and implemented

##Tasks

- [ ] Identify audience groups which we will engage with 
- [ ] [Create and build document for Twitter Engagement](https://docs.google.com/document/d/1kQrGf-AjbPNTbJNepkFGpBIAUU9C4m9OdHzgr8eJLSk/edit?usp=sharing)
- [ ] [Create and build document for Instagram Engagement](https://docs.google.com/document/d/12UWpHi7nEq6Q9eXgo5M2B0G4zIoDxAROiUixWjRLc9s/edit?usp=sharing)
- [ ] [Set up spreadsheet to monitor engagement success and set goals](https://docs.google.com/spreadsheets/d/1iF0nRnHH2--m3ZcMyzqOCzBDXZ8b7HOVkkMIesIa6ms/edit?usp=sharing)

**Comment by nathenf** [comment]
FIXED - Engagement is now an ongoing comms task
