### ISSUE TITLE
Create SOP for blog SEO and update blog

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#7]
## Acceptance

- [x] SOP is created and reviewed by @theo-cox 
- [x] Blog posts have been updated with meta-description and feature image

## Tasks

- [x] Write draft of SOP - https://docs.google.com/document/d/1v6HgJEZINhnsxrHamHgZ26Fdc-ee8GWabb8zfbTBCYc/edit#
- [x] Create Spreadsheet for Blog Posts - Added to LI Content Mastersheet under Blog Summaries
- [x] Update Feature images and meta-descriptions. This will happen once we have identified the evergreen content we want to share. See Issue #26

**Comment by nathenf** [comment]
Fixed - #26 is ongoing but another issue.
