### ISSUE TITLE
Promotion for Culture Broth retreat

### ISSUE THREAD

**Issue by nathenf** [life-itself/comms#9]
## Acceptance

- [x] Culture Broth begins

## Tasks

- [x] Discuss with Valerie - New actions to come
- [x] Valerie to record an audio - We will do this for the workshop in April not for the Feb one
- [x] Make posts for IG/FB/TW - Posting today

**Comment by nathenf** [comment]
Fixed - Begins today
